apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
  namespace: default
  labels:
    app: payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      serviceAccountName: payments-app

      containers:
        - name: payments-app
          image: ghcr.io/hashicorp-dev-advocates/payments-app-spring:1.0.0-spring
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "file:/vault/secrets/vault-secrets.properties"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://10.5.0.3:5432/payments"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
