apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
  namespace: default
  labels:
    app: payments-app
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-app-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: payments-app
type: kubernetes.io/service-account-token
