#!/bin/bash
set -euxo pipefail

if ! vault read database/creds/writer > /dev/null 2>&1; then
    fail-message "Set up a Vault \`writer\` role for the database"
fi

if ! vault read database/creds/reader > /dev/null 2>&1; then
    fail-message "Set up a Vault \`reader\` role for the database"
fi
