#!/bin/bash
set -euxo pipefail

if ! vault policy read payments-app > /dev/null 2>&1; then
    fail-message "Create a Vault policy named \`payments-app\`"
fi

if ! vault read auth/kubernetes/role/payments-app > /dev/null 2>&1; then
    fail-message "Create a Vault Kubernetes auth role named \`payments-app\`"
fi
