#!/bin/bash
set -euxo pipefail

if ! vault auth list -format=json | jq -e '."kubernetes/"' > /dev/null 2>&1; then
    fail-message "Enable the Kubernetes auth method in Vault"
fi

if ! vault read auth/kubernetes/config > /dev/null 2>&1; then
    fail-message "Configure the Kubernetes auth method with the cluster details"
fi
