version: "3"
virtualmachines:
- name: sandbox
  image: instruqt/docker-28-3
  shell: bash
  environment:
    KUBECONFIG: /root/workshop-vault-agent-devs/tmp/kubeconfig.yaml
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_TOKEN: root-token
  machine_type: n1-standard-1
